version: '3.7'
services:
    app:
      hostname: app
      container_name: app
      build:
        context: ./environments
        dockerfile: Dockerfile
        args:
          - USER_NAME="docker"
      restart: always
      tty: true # コンテナを起動し続ける
      ports:
        - "8000:8000"
        - "19000:19000"
        - "19001:19001"
        - "19002:19002"
        - "19003:19003"
        - "19004:19004"
        - "19005:19005"
        - "19006:19006"
      # depends_on:
      #   - mysql
      volumes:
        - ./src:/var/www/html
    # mysql:
    #   image: mysql:5.7
    #   hostname: mysql
    #   container_name: mysql
    #   environment:
    #       MYSQL_ROOT_PASSWORD: root
    #       MYSQL_DATABASE: sample
    #       MYSQL_USER: mysql
    #       MYSQL_PASSWORD: mysql
    #       TZ: 'Asia/Tokyo'
    #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #   volumes:
    #       - ./database/data:/var/lib/mysql
    #       - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    #       - ./database/sql:/docker-entrypoint-initdb.d
    #   ports:
    #       - 33060:3306
    #   user: 1000:1000
  # # volumes:
  # #   mysql-data:
